- .travis.yml
> Test all PostgreSQL versions from 9.2 to 9.6

- Makefile
- dbpatch-loader.sh
- sql/dbpatch.sql
- sql/noextension.sql.in
> [WIP] Allow loading dbpatch from remote connection

- .travis.yml
- Makefile
- dbpatch-loader.sh
- sql/noextension.sql.in
Adds "check", "installcheck-loader" and "installcheck-loader-noext"
Makefile rules
> Improve loader and put under automated testing

- CHANGELOG.md
- Makefile
- sql/dbpatch.sql
- test/expected/base.out
- test/sql/base.sql
> Add dbpatch_version function

- .gitignore
- .travis.yml
- CHANGELOG.md
- Makefile
- dbpatch-loader.sh
- debian/rules
Installs loader and template files outside of PostgreSQL directory
Closes #22
> Make dbpatch-loader not depend on pg_config

- dbpatch-loader.sh
Hushes informational messages coming from postgresql, keeps errors
and loader-specific informational messages
> Reduce noise in scripts loader

- .travis.yml
- Makefile
To help with publishing on PGXN
See #21
> Add "dist" rule

- CHANGELOG.md
- Makefile
> Prepare for 1.3.0 release

- CHANGELOG.md
- Makefile
Documentation on PGXN lies about accepting tgz files ...
> Have 'make dist' produce a .zip file as needed by PGXN

- CHANGELOG.md
- dbpatch-loader.sh
> Allow schema loader to output loading statement to standard output

- CHANGELOG.md
- Makefile
> Set version and release date for 1.4.0, allow upgrades from 1.3

- .travis.yml
- CHANGELOG.md
- Makefile
Test support for PostgreSQL 10/11
> PostgreSQL 10/11 support

- CHANGELOG.md
- dbpatch-loader.sh
> Include extension name in loader progress message

- CHANGELOG.md
- doc/dbpatch.md
- sql/dbpatch.sql
So that clients can hush them via client_min_messages session var
> Use NOTICE instead of INFO for informational messages

- .travis.yml
> [travis] Use Bionic for testing

- CHANGELOG.md
- Makefile
See #51
NOTE: I tried to push directly to master but robots
enforce a policy of forbidding that...
> Set final version to 1.5.0 and finalize CHANGELOG

- .github/workflows/test.yml
- README.md
Second attempt, this time requesting pull from a branch
on official repository. Superceeds #56
> [github action] Add CI configuration and badge

- .github/workflows/test.yml
- Makefile
- debian/rules
Fixes #62
Includes automated testing.
Probably to be backported to latest release branch
> Make sure NO postgresql package includes loader and template

- .travis.yml
- Makefile
- debian/rules
> [1.5] Make sure NO postgresql package includes loader and template

- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
Very early step here, mostly trying out the github action
workflow...
Ref: https://github.com/linz/linz-software-repository/issues/19
> Use linz-software-repository github action to build packages on every commit

- .github/workflows/test.yml
Fixes tag pushing and merging of debian/changelog
> Use @v4 version of linz-software-repository action

- .github/workflows/test.yml
At 12:00 UTC on Sunday, which is around midnight in New Zealand. This
ensures the run will be done well before the new work week starts.
> feat: Run pipeline weekly

- .github/workflows/test.yml
- .travis.yml
- test/ci/test_all_upgrades.bash
> tests: Lint upgrade test script

- test/ci/test_all_upgrades.bash
> tests: Include all buildable versions in upgrade test

- .github/workflows/test.yml
> build: All PostgreSQL versions

- .github/workflows/test.yml
- CHANGELOG.md
> build: Drop Ubuntu 18.04 support

- bump-nix.bash
- nixpkgs.json
- shell.nix
> build: Bump nixpkgs

- nix/sources.json
> build: Use unstable nixpkgs
